# metal_stdlib_stubs.py
# Python stubs for Metal Standard Library functions

# --- Math Functions ---
def acos(x): ...
def acosh(x): ...
def asin(x): ...
def asinh(x): ...
def atan(y_over_x): ...
def atan2(y, x): ...
def atanh(x): ...
def ceil(x): ...
def copysign(x, y): ...
def cos(x): ...
def cosh(x): ...
def cospi(x): ...
def divide(x, y): ...
def exp(x): ...
def exp2(x): ...
def exp10(x): ...
def fabs(x): ...
def fdim(x, y): ...
def floor(x): ...
def fma(a, b, c): ...
def fmax(x, y): ...
def fmax3(x, y, z): ...
def fmedian3(x, y, z): ...
def fmin(x, y): ...
def fmin3(x, y, z): ...
def fmod(x, y): ...
def fract(x): ...
def frexp(x, exponent): ...
def ilogb(x): ...
def ldexp(x, k): ...
def log(x): ...
def log2(x): ...
def log10(x): ...
def modf(x, intval): ...
def nextafter(x, y): ...
def pow(x, y): ...
def powr(x, y): ...
def rint(x): ...
def round(x): ...
def rsqrt(x): ...
def sin(x): ...
def sincos(x, cosval): ...
def sinh(x): ...
def sinpi(x): ...
def sqrt(x): ...
def tan(x): ...
def tanh(x): ...
def tanpi(x): ...
def trunc(x): ...

# --- Common Functions ---
def clamp(x, minval, maxval): ...
def mix(x, y, a): ...
def saturate(x): ...
def sign(x): ...
def smoothstep(edge0, edge1, x): ...
def step(edge, x): ...

# --- Integer Functions ---
def abs(x): ...  # renamed to avoid clash with fabs
def absdiff(x, y): ...
def addsat(x, y): ...
def clz(x): ...
def ctz(x): ...
def extract_bits(x, offset, bits): ...
def hadd(x, y): ...
def insert_bits(base, insert, offset, bits): ...
def mad24(x, y, z): ...
def madhi(a, b, c): ...
def madsat(a, b, c): ...
def max(x, y): ...
def max3(x, y, z): ...
def median3_int(x, y, z): ...
def min(x, y): ...
def min3(x, y, z): ...
def mul24(x, y): ...
def mulhi(x, y): ...
def popcount(x): ...
def reverse_bits(x): ...
def rhadd(x, y): ...
def rotate(v, i): ...
def subsat(x, y): ...

# --- Relational Functions ---
def all(x): ...
def any(x): ...
def isfinite(x): ...
def isinf(x): ...
def isnan(x): ...
def isnormal(x): ...
def isordered(x, y): ...
def isunordered(x, y): ...
def not_fn(x): ...  # renamed because `not` is a keyword
def select(a, b, c): ...
def signbit(x): ...
